name: Workflow for Codecov
on: [push, pull_request]
jobs:
  coverage-test:
    runs-on: ubuntu-latest
    env:
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGDATABASE: postgres_db
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres_db
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with: {node-version: 16}
      - uses: huaxk/postgis-action@v1
        with:
          postgresql version: '11'
          postgresql db: $PGDATABASE
          postgresql user: $PGUSER
          postgresql password: $PGPASSWORD
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
