name: Workflow for Codecov
on: [push, pull_request]
jobs:
  coverage-test:
    runs-on: ubuntu-latest
    env:
      SNAPLET_ACCESS_TOKEN: ${{ secrets.SNAPLET_ACCESS_TOKEN }}
      SNAPLET_DATABASE_ID: <snaplet-database-id>
      PGHOST: localhost
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGDATABASE: postgres_db
      DATABASE_URL: postgres://localhost:5432/postgres_db
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node 16
        uses: actions/setup-node@v3
        with: {node-version: 16}
      - name: Postgres Docker
        uses: harmon758/postgresql-action@v1
        with:
          postgresql version: '11'
          postgresql db: $PGDATABASE
      - name: Install dependencies
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
